name: Unit Tests

on:

  pull_request:
    branches: [ "main" ]
    types: [ "opened", "edited", "synchronize" ]

  workflow_dispatch:
    inputs:
      start_deploy:
        type: boolean
        description: Are you sure to start this action?
        default: false

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: [3.8, 3.9, "3.10", 3.11]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Set up Poetry
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: 1.5.1

    - name: Install dependencies
      run: |
        poetry install --with=tests

    - name: Run pytest
      run: |
        poetry run pytest -v
